# See https://developers.cloudflare.com/workers/wrangler/configuration/
name = "hungrytapir-store"
compatibility_date = "2023-06-13"
compatibility_flags = ["streams_enable_constructors"]

services = [
  { binding = "CONFIGSTORE_WORKER", service = "hungrytapir-store-config-test" }
]

kv_namespaces = [
    { binding = "CONTENT_STORE", id = "079af1ba003a4629bb5565a4a96e2de4", preview_id = "fbabe5eb5d7f43cd9c336fa1656473d1" },
]

[env.prod]
name = "hungrytapir-store"
