on:
    push:
        paths-ignore:
            - 'README.md'
        paths:
            - 'functions/**'
            - 'lambdas/**'

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        name: Deploy to Cloudflare Pages
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Build
              run: npm install && npm run build
            - name: Load secrets from 1Password
              uses: 1Password/load-secrets-action@v1
              env:
                  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_TEST }}
                  CLOUDFLARE_API_TOKEN: 'op://${{ vars.VAULT_NAME }}/Cloudflare API Token/credential'
                  CLOUDFLARE_ACCOUNT_ID: 'op://${{ vars.VAULT_NAME }}/Cloudflare API Token/username'
            - name: Publish
              uses: cloudflare/wrangler-action@2.0.0
              with:
                  apiToken: '${{ env.CLOUDFLARE_API_TOKEN }}'
                  accountId: '${{ env.CLOUDFLARE_ACCOUNT_ID }}'
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
