name: Refresh trigger for test env
on:
  schedule:
    - cron: 0 23 * * *
jobs:
  update-kv-store:
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets from 1Password
        uses: 1Password/load-secrets-action@v1
        env:
            OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_TEST }}
            BASIC_AUTH_USERNAME: 'op://${{ vars.VAULT_NAME }}/HT Basic/username'
            BASIC_AUTH_PASSWORD: 'op://${{ vars.VAULT_NAME }}/HT Basic/credential'
      - name: Set HOST and PURGE
        run: |
            echo "HOST=https://develop.hungrytapir-store.pages.dev" >> $GITHUB_ENV
      - name: Post request on Refresh Content API
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ env.HOST }}/api/refresh-content'
          method: 'POST'
          username: '${{ env.BASIC_AUTH_USERNAME }}'
          password: '${{ env.BASIC_AUTH_PASSWORD }}'
          timeout: 120000